### ISSUE TITLE
Prevent placement of targets outside targeting square

### ISSUE THREAD

**Issue by pmarathakis** [Harmonus/HMS_SlicerModule#17]
The software currently allows the user to place targets outside the targeting square. The system doesn't print the guide and informs the user (it might only be in the console).
We should instead not allow the placement of targets outside the targeting square

**Comment by nicoleaucoin** [comment]
Check against needle length for the z range?

**Comment by nicoleaucoin** [comment]
Recommended biopsy gun is 170mm, AMIGO accuracy test biopsy needle is 200mm.

**Comment by nicoleaucoin** [comment]
Green zone calculation is wrong in certain cases (appears on wrong side of frame, check IS vs SI scans)

**Comment by nicoleaucoin** [comment]
Redone and working for RAS coordinate grid and markers.
