### ISSUE TITLE
Communication error reporting

### ISSUE THREAD

**Issue by nicoleaucoin** [Harmonus/HMS_SlicerModule#182]
- [x] The software shall alert the user if it fails to receive acknowledgement from MRI/PACS

**Comment by nicoleaucoin** [comment]
Can I catch/report:
Debug: In C:\S_4_6_2\OpenIGTLink\Source\igtlClientSocket.cxx, line 67
igtl::ClientSocket (000002BCD0DADA50): Failed to connect to server localhost:18944

**Comment by nicoleaucoin** [comment]
Mostly report when expecting an ACK and don't get it.

**Comment by pmarathakis** [comment]
Open SW
click connect
open Manual_Client.exe (A separate instance)
In slicer, deactivate the IGT node
click connect again

**Comment by pmarathakis** [comment]
Proposed fix:
in HMS_Client.cpp
add on line 10:
_socket.CloseSocket(1);
