### ISSUE TITLE
DICOM assignment screen buttons cut off

### ISSUE THREAD

**Issue by pmarathakis** [Harmonus/HMS_SlicerModule#196]
DICOM asasignment screen buttons (reset, check and accept, cancel)  are cut off on the left & right

**Comment by nicoleaucoin** [comment]
UI needs to be redone, too hard coded.

**Comment by nicoleaucoin** [comment]
Also: fix the 2d slice viewer so that it shows an axial view (fix the view nodes in the dicom assignment scene).

**Comment by nicoleaucoin** [comment]
squashed two commits, ready to pull request if testing on high res screen passes.

**Comment by nicoleaucoin** [comment]
Merged, test on hi res laptop then close.

**Comment by nicoleaucoin** [comment]
Tested on hi res laptop, looks good.
