### ISSUE TITLE
External DICOM import lines are cutting off

### ISSUE THREAD

**Issue by pmarathakis** [Harmonus/HMS_SlicerModule#198]
External DICOM import screen is cutting off the tops and bottom of each line of the scans

**Comment by nicoleaucoin** [comment]
Reported by someone else on the Slicer dev list:
https://discourse.slicer.org/t/overlapped-text-in-windows-10/1153

They're working on a new stable release right now, I'm keeping an eye on the release schedule to see if we can switch to it.

**Comment by nicoleaucoin** [comment]
clicking on >> button in the menu bar of the wiget and setting Density to Comfortable:

**Comment by nicoleaucoin** [comment]
Check screen resolution, change table density, merged.
