### ISSUE TITLE
Visualization of grid holes on target screen

### ISSUE THREAD

**Issue by pmarathakis** [Harmonus/HMS_SlicerModule#228]
Dr Tuncali would prefer to be able to visualize the grid hole locations in the Axial view in the Target Screen.

**Comment by nicoleaucoin** [comment]
Need to set the visibility to only show in View1 and Red.
To set target grid hole a different colour, will need to apply scalars to the tubes.

**Comment by nicoleaucoin** [comment]
Todo: flag on NGF present to only show one tube.
