### ISSUE TITLE
Grid hole visualization for target

### ISSUE THREAD

**Issue by pmarathakis** [Harmonus/HMS_SlicerModule#230]
Dr Tuncali would like a visual representation of the grid in place of the 3D viewer in the selection and confirmation screens with a large marker showing which grid hole should be used during insertion, as well as the depth of insertion.

**Comment by nicoleaucoin** [comment]
Add grid coordinate letters and numbers as vtkVectorText

**Comment by nicoleaucoin** [comment]
For selection and confirmation, only have the target grid coords in the vector text?

**Comment by nicoleaucoin** [comment]
Consider colouring lightly all tubes in row and column leading to the target one

**Comment by nicoleaucoin** [comment]
Merged.
