### ISSUE TITLE
Self check at start up - risk mitigation

### ISSUE THREAD

**Issue by nicoleaucoin** [Harmonus/HMS_SlicerModule#75]
Add Risk analysis checks to start up check.

- [x] disk space is sufficient (> 10Gb)
- [x] The software shall perform a self check at start up to check the integrity of the code (checksum).

**Comment by nicoleaucoin** [comment]
Disk space check available in Qt5. Look at QSystemStorageInfo  vs QStorageInfo

**Comment by pmarathakis** [comment]
To calculate checksum values, download FCIV from https://support.microsoft.com/en-us/help/841290/availability-and-description-of-the-file-checksum-integrity-verifier-u

To run checksum calculator:
pathtoFCIV/FCIV - md5 pathtofile/file.exe
to get checksum for a file
or
pathtoFCIV/FCIV - md5 pathtofolder
to get checksum for all files in a folder

**Comment by nicoleaucoin** [comment]
Free space:
if platform.system() == 'Windows':
        free_bytes = ctypes.c_ulonglong(0)
        ctypes.windll.kernel32.GetDiskFreeSpaceExW(ctypes.c_wchar_p(dirname), None, None, ctypes.pointer(free_bytes))
        return free_bytes.value / 1024 / 1024

**Comment by nicoleaucoin** [comment]
Do the python compiled files.

**Comment by nicoleaucoin** [comment]
Merged.
